### ISSUE TITLE
Webpack Cannot Resolve Module 'fs'

### ISSUE THREAD

**Issue by imjakechapman** [Mikhus/domurl#25] opened 2016-08-01 22:13 UTC
`require('domurl')`

Gives me `ModuleNotFoundError in 
            Module not found: Error: Cannot resolve module 'fs' in /node_modules/domurl`

**Comment by Mikhus** [comment] 2016-08-04 13:40
Could you please check if it is still reproducible with the latest release v2.1.2?

Thank you in advance!

**Comment by pracucci** [comment] 2016-08-09 10:21
I have the same issue and I can reproduce it with the latest release v2.1.6.

The problem is how Webpack resolves `require()` calls. Webpack resolves `require()` at compile time and not a run time, so it actually requires a module even if the code will never reach that specific point. I do believe a possible solution would be get a reference to the `require()` function and do the requires with it.

For instance, you could try to change the following code:
````
        var currUrl = isNode ? ('file://' +
            (process.platform.match(/^win/i) ? '/' : '') +
            require('fs').realpathSync('.')
        ) : document.location.href;

        if (!url) {
            url = currUrl;
        }

        if (isNode) {
            link = require('url').parse(url);
        }
```

to:
```
        var nodeRequire = isNode ? require : null;
        var currUrl = isNode ? ('file://' +
            (process.platform.match(/^win/i) ? '/' : '') +
            nodeRequire('fs').realpathSync('.')
        ) : document.location.href;

        if (!url) {
            url = currUrl;
        }

        if (isNode) {
            link = nodeRequire('url').parse(url);
        }
```

**Comment by Mikhus** [comment] 2016-08-10 20:08
Thank you, @pracucci . I would be very appreciate if you can propose a contribution (pull request) which would contain your suggestion, just to keep your authorship in the history of this module contributions. That should not take too much time. BTW, if you do not want it to do for any reason, just let me know. Thank you in advance,
Mike

**Comment by pracucci** [comment] 2016-08-11 09:12
I've submitted the PR #26.
Marco

**Comment by Mikhus** [comment] 2016-08-12 10:23
Fixed in https://github.com/Mikhus/domurl/pull/26
Target release: 2.1.7

@pracucci, Thank you very much for the contribution!

**Closed by Mikhus** 2016-08-12 10:23 UTC
